info:
  scm-url: @scm.url@
  stage: test

logging:
  file: target/boot-admin-sample.log

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8080

endpoints:
  health:
    sensitive: false
