spring:
  application:
    name: eureka-example
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
